### ISSUE TITLE
Plugin crashing in Sublime text 3

### ISSUE THREAD

**Issue by crisbeto** [aziz/PlainNotes#56]
I've been using the plugin for a while without issues, however a few hours ago Sublime started freezing a few seconds after startup. I managed to track the issue down to `PlainNotes`, although I'm not sure exactly what is causing it. I'm using Sublime Text 3 build 3126 64bit on Windows 10 and v0.2.6 of the notes plugin. I've tried the following without success:
- Reinstalling Sublime.
- Reinstalling the plugin.
- Clearing the `.brain` folder in the `SublimeNotes` directory.
- Deleting the `SublimeNotes` directory.

The only thing that seems to help is if I add `PlainNotes` to the `ignored_packages`.

**Comment by aziz** [comment]
I'm using it on macOS with build 3125 which the latest from the dev channel and it works just fine. 
let's see if this is limited to Windows or the latest version or something else.

**Comment by crisbeto** [comment]
If it helps, here's all the other plugins I'm using:

```
"Colorsublime",
"DocBlockr",
"Emmet",
"ES6-Toolkit",
"Git Config",
"Git Conflict Resolver",
"GitHub Flavored Markdown Preview",
"Gitignored File Excluder",
"HTML-CSS-JS Prettify",
"INI",
"JavaScriptNext - ES6 Syntax",
"JsFormat",
"JSON Reindent",
"Markdown Preview",
"MarkdownHighlighting",
"Monokai Extended",
"Package Control",
"PlainNotes",
"Predawn",
"Pretty JSON",
"ProjectManager",
"PxToEm",
"Razor",
"SCSS",
"SideBarEnhancements",
"SublimeHighlight",
"SublimeLinter",
"SublimeLinter-contrib-tslint",
"SublimeLinter-csslint",
"SublimeLinter-jshint",
"Theme - Augmented Reaction",
"Theme - Minimal",
"Theme - Numix",
"Theme - Spacegray",
"TypeScript",
"VBScript",
"Zeal"
```

**Comment by aziz** [comment]
Could you do me a favor and try these steps. I don't have a windows vm at the moment and I can't test it myself. 

1. uninstall the plugin
2. delete the cache folder for this plugin. on Mac you can run command `browse packages` and then go the parent folder. go inside the `Cache` folder and delete `PlainNotes` folder if you see it
3. install the plugin again.

**Comment by OdatNurd** [comment]
Just to report in, I'm experiencing the same issue across all three platforms; Windows 7 x64, Linux x86 and MacOS 10.10.5. Having just this plugin (and PackageControl) installed is enough to hang plugin_host; killing plugin_host predictably makes Sublime responsive again.

**Comment by aziz** [comment]
I've released 0.2.7 and it hopefully fixes the issue

**Comment by crisbeto** [comment]
Seems like it's taking a while for it to propagate, Sublime still lists 0.2.6. I'll try it out again in an hour or so. Regarding the previous comment, it doesn't look like Windows has a `Cache` folder, it only has a Package Control cache, but AFAIK that's for the search results.

**Comment by OdatNurd** [comment]
Probably redundant at this point, but just for documentation purposes, as @crisbeto mentioned I can't see a Cache folder either; however the steps you outlined did not resolve the issue on Linux or MacOS.

**Comment by crisbeto** [comment]
Thanks, 0.2.7 works.
